### ISSUE TITLE
Version 1.15.8.2

### ISSUE THREAD

**Issue by rofafor** [openresty/docker-openresty#118]
A new Openresty version 1.15.8.2 is released with important CVE fixes. I'd like to see this one as an official Docker image as well.

**Comment by neomantra** [comment]
I just pushed [this commit](5ca0e4d8159c0b304a183a7bdad0cd51f54a4d7f) which brings OpenResty 1.15.8.2 to the build-from-source flavors (`alpine`, `bionic`, and `xenial`).  This is building on Travis now and images should appear on Docker Hub as _master_ tags within the hour.

Once upstream packages for CentOS and Debian are released, I will update the corresponding image flavors.

There have been some changes/issues with OpenSSL treatment and there is further work needed there to appropriately support the `ssl_session_(store|fetch)_by_lua*` directives (related to this [OpenResty patch](https://github.com/openresty/lua-nginx-module/commit/d3dbc0c8102a9978d649c99e3261d93aac547378)).  This work dovetails with #117, wherein we build OpenSSL ourselves rather than using the system packages.

Let me know if you have any issues with these packages.

**Comment by rofafor** [comment]
The version specific tags like *1.15.8.2-alpine-fat* are still missing from those build-from-source flavors.

**Comment by neomantra** [comment]
I just manually tagged these images Travis-built from commit 5ca0e4d .  There is no corresponding git tag.

```
openresty/openresty:1.15.8.2-0-alpine
openresty/openresty:1.15.8.2-0-alpine-fat
openresty/openresty:1.15.8.2-0-alpine-fat-nosse42
openresty/openresty:1.15.8.2-0-alpine-nosse42
openresty/openresty:1.15.8.2-0-bionic
openresty/openresty:1.15.8.2-0-bionic-nosse42
openresty/openresty:1.15.8.2-0-xenial
openresty/openresty:1.15.8.2-0-xenial-nosse42
openresty/openresty:1.15.8.2-alpine
openresty/openresty:1.15.8.2-alpine-fat
openresty/openresty:1.15.8.2-alpine-fat-nosse42
openresty/openresty:1.15.8.2-alpine-nosse42
openresty/openresty:1.15.8.2-bionic
openresty/openresty:1.15.8.2-bionic-nosse42
openresty/openresty:1.15.8.2-xenial
openresty/openresty:1.15.8.2-xenial-nosse42
```

**Comment by rofafor** [comment]
Thanks!

**Comment by neomantra** [comment]
I just manually tagged the following images Travis-built from commit  340771c .  There is no corresponding git tag.

```
openresty/openresty:1.15.8.2-1-alpine
openresty/openresty:1.15.8.2-1-alpine-fat
openresty/openresty:1.15.8.2-1-alpine-fat-nosse42
openresty/openresty:1.15.8.2-1-alpine-nosse42
openresty/openresty:1.15.8.2-1-bionic
openresty/openresty:1.15.8.2-1-bionic-nosse42
openresty/openresty:1.15.8.2-1-xenial
openresty/openresty:1.15.8.2-1-xenial-nosse42
openresty/openresty:1.15.8.2-alpine
openresty/openresty:1.15.8.2-alpine-fat
openresty/openresty:1.15.8.2-alpine-fat-nosse42
openresty/openresty:1.15.8.2-alpine-nosse42
openresty/openresty:1.15.8.2-bionic
openresty/openresty:1.15.8.2-bionic-nosse42
openresty/openresty:1.15.8.2-xenial
openresty/openresty:1.15.8.2-xenial-nosse42
```
